_HOST_URL_PATH = 'http://127.0.0.1:5000'
_BASE_URL_PATH = '/api/v1'

USER_URL_PATH = f'{_BASE_URL_PATH}/users'
DB_URL_PATH = f'{_BASE_URL_PATH}/db'
EVENT_URL_PATH = f'{_BASE_URL_PATH}/events'


TEST_USER_URL_PATH = f'{_HOST_URL_PATH}{_BASE_URL_PATH}/users'
TEST_EVENT_URL_PATH = f'{_HOST_URL_PATH}{_BASE_URL_PATH}/events'